# Generated by Django 5.2.5 on 2025-09-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_texto', models.CharField(max_length=200)),
                ('opcion_a', models.CharField(max_length=100)),
                ('opcion_b', models.CharField(max_length=100)),
                ('opcion_c', models.CharField(max_length=100)),
                ('opcion_d', models.CharField(max_length=100)),
                ('respuesta_correcta', models.CharField(max_length=100)),
            ],
        ),
    ]
